spring:
   profiles: peer1
   application:
      name: service-registry
server:
   port: 8761
eureka:
   client:
      service-url:
         defaultZone: http://admin:admin@${eureka.instance.hostname}:8762/eureka/
      fetch-registry: true
      register-with-eureka: true
   instance:
      hostname: localhost
      lease-expiration-duration-in-seconds: 90
      lease-renewal-interval-in-seconds: 30
---
spring:
   profiles: peer2
   application:
      name: service-registry
server:
   port: 8762
eureka:
   client:
      service-url:
         defaultZone: http://admin:admin@${eureka.instance.hostname}:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
   instance:
      hostname: localhost
      lease-expiration-duration-in-seconds: 90
      lease-renewal-interval-in-seconds: 30
